In [1]:
import numpy as np
from neowise_ML import score

In [2]:
data_folder = "../data/"

file = np.load(data_folder + "test_triplets.npz")
cutouts = file["data"]

y_probs = score(data = cutouts, logits=True)
print(y_probs)

[[7.8541314e-04 4.8283632e-03 1.8371345e-03 9.9254906e-01]
 [7.4332877e-04 5.6405552e-05 9.5256567e-03 9.8967463e-01]
 [8.4458443e-05 6.6233578e-04 8.8406581e-01 1.1518736e-01]
 [8.4307372e-05 1.4573274e-06 9.9780446e-01 2.1098282e-03]
 [1.1221810e-01 8.8756037e-01 8.0784730e-06 2.1350938e-04]
 [3.2444234e-04 9.9967456e-01 9.1632444e-09 1.0073198e-06]
 [9.9193901e-01 1.6941929e-04 1.6865485e-04 7.7229152e-03]
 [9.9886584e-01 9.8364754e-04 6.5780165e-05 8.4750885e-05]]
